"""Fix model indentation

Revision ID: 350ddaece45b
Revises: cdd392dd8073
Create Date: 2025-05-28 09:03:13.914477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350ddaece45b'
down_revision = 'cdd392dd8073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
